#line 2 "./query.cpp"

#line 4 "./query.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[207] =
    {   0,
        0,    0,   16,   14,   13,   13,   14,   14,    5,   14,
        9,   12,   12,    0,    0,    4,    0,    0,    0,    5,
        9,    0,    0,    0,    0,    0,    0,    9,   12,    0,
       12,    0,    5,    0,    4,    0,    5,    0,    0,    0,
        0,    7,   11,    0,   12,    0,    0,    2,    2,    0,
        5,    8,    0,    0,    0,    0,    0,    0,    0,   10,
        2,   12,    0,    6,    2,    2,    0,    2,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
       12,    1,    2,    2,    2,    2,    2,    0,    0,    0,
        0,    0,    0,    2,    0,    0,    1,    2,    2,    2,

        2,    0,    0,    0,    0,    0,    2,    0,    0,    1,
        2,    4,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    2,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    6,    2,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    3,    0,
        0,    0,    0,    0,    0,    2,    0,    0,    0,    0,
        0,    0,    0,    2,    2,    0,    0,    0,    2,    2,

        0,    2,    0,    2,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,   12,
       13,   14,    1,   15,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   17,   16,   16,   16,
        1,    1,    1,    1,   18,    1,   19,   19,   19,   19,

       19,   19,   19,   20,   19,   19,   19,   19,   19,   19,
       19,   21,   19,   19,   22,   23,   19,   19,   24,   19,
       19,   19,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[25] =
    {   0,
        1,    2,    2,    3,    2,    1,    4,    5,    6,    7,
        8,    1,    1,    1,    9,    7,    7,   10,    7,    7,
        7,    7,    7,    7
    } ;

static yyconst flex_int16_t yy_base[243] =
    {   0,
        0,    0,  591,  766,  766,  766,  571,   15,   25,   25,
       43,   58,  558,  561,    0,   42,  561,   69,   81,  556,
       63,   62,   76,    0,   98,  106,  118,  118,    0,   76,
      542,  556,   84,  136,  148,  160,   29,  172,  549,  189,
      548,  766,  207,  219,  540,    0,  550,  231,   18,   95,
      549,  766,    0,  553,   35,  254,  267,    0,  534,  281,
      293,   59,  547,   46,  545,  311,  540,   87,  526,  528,
       75,  334,  101,  353,    0,  116,  509,  508,  371,  521,
      518,  513,  508,  508,  389,   96,  101,  506,  412,    0,
      492,  115,  493,  420,  494,  491,  491,  486,  437,  106,

      121,  487,  469,    0,  447,  123,  465,  103,  470,  470,
      467,  138,  140,  452,  438,  145,  488,  503,  443,    0,
      428,  425,  422,  148,  153,  157,  145,  153,  414,  162,
      412,  162,  174,  178,  181,  518,    0,  395,  536,  394,
      394,  393,    0,    0,  384,  159,  368,  176,  187,  375,
      373,  356,  212,  192,  207,  221,  222,  214,  255,  204,
      356,  251,  266,  263,  267,  347,  219,  352,  271,  272,
      278,  290,  243,  266,  540,    0,  332,  333,    0,  545,
      284,  342,  321,  329,  327,  561,  298,  331,  316,  335,
      340,  278,  344,  566,  571,    0,  408,  415,  576,  581,

      316,  586,    0,  591,  596,  766,  604,  612,  616,  623,
      630,  270,  637,  644,  651,  658,  665,  675,  684,  688,
      693,  258,  697,  704,  708,  191,  140,  128,  125,   91,
      715,  719,   48,  724,  729,  733,  738,   20,  743,  748,
      752,  757
    } ;

static yyconst flex_int16_t yy_def[243] =
    {   0,
      206,    1,  206,  206,  206,  206,  207,  207,  206,  208,
      206,   11,   12,  207,  209,  207,  206,  210,  211,    9,
        9,   21,  208,  212,   23,  213,  214,   11,   12,   28,
       12,  209,  206,  210,  215,  215,    9,  211,  212,  206,
      206,  206,  213,  216,   12,  217,   38,  206,   48,   34,
        9,  206,   40,  218,   40,   40,  219,   56,   56,  214,
      206,   12,  220,   36,  221,  206,  206,   66,   34,  218,
       56,  219,   56,  206,  222,   72,   56,   56,  206,  206,
       12,  223,   48,  221,  206,   85,  206,   34,   74,   89,
       89,  224,   56,  206,  206,  206,  225,   66,   34,   34,

      206,   34,   89,  226,  206,   56,  206,  227,  206,  209,
       85,   34,  206,   50,   89,  226,  206,  105,  206,  118,
      118,  206,   56,  107,  227,  227,  126,  227,   99,  206,
       34,   89,  117,  117,  117,  118,  136,  136,   56,  136,
      206,  206,  228,  229,  126,  126,  126,  126,   34,  206,
       34,   89,  117,   89,   89,   89,   89,   56,   89,  230,
      206,  228,  231,  126,  126,  126,  126,   34,  117,   56,
      230,  230,  172,  230,  232,  233,  126,  126,   34,  117,
       56,  172,  172,  172,  172,  234,  235,  180,   56,  172,
      172,  172,  172,  236,  237,  238,  172,  172,  228,  239,

      240,  241,  105,  242,  242,    0,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206
    } ;

static yyconst flex_int16_t yy_nxt[791] =
    {   0,
        4,    5,    6,    4,    4,    4,    7,    8,    4,    9,
        4,   10,    4,    4,    4,   11,   11,    7,   12,   13,
       12,   12,   12,   12,   16,   38,  201,   68,   23,   15,
       17,   18,   19,   24,   20,   50,   72,   72,   51,   15,
       21,   21,   14,   22,   22,   22,   22,   22,   22,   26,
       27,   16,   21,   47,  187,   83,   15,   15,   28,   28,
       14,   29,   29,   29,   29,   29,   29,   22,  206,   80,
       38,   22,   21,   30,   30,   14,   14,   22,   22,  206,
       81,   55,  206,   15,  206,   22,   14,   14,   14,   17,
       35,   30,   30,   33,   38,   15,   86,  171,   14,   40,

       40,   14,   14,   38,   69,  100,   41,   55,  206,   65,
      101,   42,   14,   14,   65,   34,   67,   76,   76,  126,
       15,  104,   75,   14,   14,   14,  127,   36,  206,   65,
      113,  163,   15,  122,  162,   14,   30,   30,   30,   30,
       30,   30,   18,   38,  123,   47,  125,  112,   65,  130,
       15,  104,   75,   14,   18,   47,  206,   48,  206,  143,
      144,  125,   15,  143,  144,   14,   18,   38,  146,  147,
       65,  150,  122,  145,   15,  125,  148,   14,   14,   14,
       74,   75,  165,  152,   74,   75,   15,   74,   75,   14,
       53,   53,  125,   54,   47,   55,  149,  116,   56,  167,

      117,   57,  119,  153,   58,   58,   55,   58,   59,   58,
       58,   58,   58,   26,   38,  117,   34,  119,   74,   75,
      172,   15,  117,  170,   14,   18,   60,  173,   49,  117,
      117,  119,  119,   15,  169,  125,   14,   18,   47,   65,
       66,   67,  178,  103,  115,   15,   68,   68,   14,   68,
       68,   68,   68,   68,   68,   73,   73,  143,  144,  171,
       74,   75,   41,  117,   92,  119,  183,   42,   76,   76,
      176,   54,  143,  144,  176,  132,   39,   74,   75,  125,
      117,  181,  184,  125,  104,   75,   77,   14,   14,  185,
       36,  180,  117,  189,  197,   15,  104,   75,   14,   18,

       60,   65,   68,   67,  143,  144,  182,   15,   79,   79,
       14,   79,   79,   79,   79,   79,   79,   18,   47,   65,
       85,   67,  104,   75,  117,   15,   86,   86,   14,   86,
       86,   86,   86,   86,   86,   72,   72,  171,   54,  176,
      176,  142,  196,  171,  191,  192,   57,  196,  125,  125,
      193,  171,  134,   77,   72,   72,  171,   54,  190,   55,
      171,  179,   89,  177,  174,   57,  142,  198,   90,   90,
       55,   90,   91,   90,   90,   90,   90,   18,   60,   65,
       86,   67,  168,   65,  166,   15,   94,   94,   14,   94,
       94,   94,   94,   94,   94,   18,   47,   65,   99,   67,

      164,  161,  160,   15,  100,  100,   14,  100,  100,  100,
      100,  100,  100,   73,   73,  196,  159,  157,   74,   75,
       41,  151,  196,  149,  171,   42,   18,   60,   65,  100,
       67,  171,  142,  141,   15,  107,  107,   14,  107,  107,
      107,  107,  107,  107,   47,   65,  112,   67,   73,   73,
      140,   54,  139,   74,   75,  117,  118,  119,  132,   57,
       42,  131,  120,  120,   55,  120,  121,  120,  120,  120,
      120,   18,   60,   65,   34,   67,  129,   46,  128,   15,
      124,  124,   14,  124,  124,  124,  124,  124,  124,   73,
       73,  115,   54,  114,   55,  111,  117,  133,   46,  109,

       57,   42,  108,  134,  134,   55,  134,  135,  134,  134,
      134,  134,  136,  106,  103,  102,   65,   98,  137,  137,
       46,  137,  138,  137,  137,  137,  137,  154,   96,   95,
       93,   78,   71,  155,  155,   88,  155,  156,  155,  155,
      155,  155,   55,  206,  117,  158,  143,  144,   65,   87,
       67,   74,   75,   65,   46,  122,   78,   71,   51,   64,
       62,   42,   52,   46,   45,   37,  188,  143,  144,   65,
       33,   67,  143,  144,   65,   15,   67,  143,  144,   65,
       31,   67,  143,  144,   65,   15,   67,  143,  144,   65,
      206,   67,  143,  144,   65,  206,   67,  143,  144,   65,

      206,   67,  143,  144,  206,  206,  206,   14,   14,  206,
       14,  206,   14,   14,   25,  206,  206,   25,   25,   32,
      206,  206,   32,  206,  206,   32,   34,   34,  206,   34,
      206,   34,   34,   36,   36,  206,   36,  206,   36,   36,
       43,   43,  206,   43,  206,   43,   43,   44,   44,  206,
       44,  206,   44,   44,   49,   49,  206,   49,  206,   49,
       49,   61,   61,  206,   61,  206,   61,   61,   63,  206,
      206,   63,  206,  206,   63,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   56,  206,  206,  206,  206,
       56,   82,   82,  206,   82,  206,  206,   82,   84,   84,

       97,   97,  206,   97,  206,  206,   97,  105,  105,  206,
      105,  110,  110,  206,  110,  206,  206,  110,  175,  175,
      206,  175,  186,  186,  186,  186,  186,  194,  194,  194,
      194,  194,  195,  195,  206,  195,  199,  199,  199,  199,
      199,  200,  200,  200,  200,  200,  202,  202,  202,  202,
      202,  203,  203,  206,  203,  204,  204,  204,  204,  204,
      205,  205,  205,  205,  205,    3,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206
    } ;

static yyconst flex_int16_t yy_chk[791] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   49,  238,   49,   10,    8,
        9,    9,    9,   10,    9,   37,   55,   55,   37,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   11,
       11,   16,   11,   64,  233,   64,   16,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   21,   62,
       21,   22,   21,   12,   12,   18,   18,   22,   22,   23,
       62,   71,   71,   18,   23,   30,   18,   19,   19,   33,
       19,   30,   30,   33,   68,   19,   68,  230,   19,   25,

       25,   50,   50,   86,   50,   86,   25,   73,   73,   87,
       87,   25,   26,   26,  100,   26,  100,   76,   76,  108,
       26,   92,   92,   26,   27,   27,  108,   27,   76,  101,
      101,  229,   27,  106,  228,   27,   28,   28,   28,   28,
       28,   28,   34,   34,  106,  112,  227,  112,  113,  113,
       34,  116,  116,   34,   35,   35,  124,   35,  124,  125,
      125,  127,   35,  126,  126,   35,   36,   36,  127,  128,
      130,  130,  132,  126,   36,  146,  128,   36,   38,   38,
      133,  133,  146,  132,  134,  134,   38,  135,  135,   38,
       40,   40,  148,   40,  149,   40,  149,  226,   40,  148,

      154,   40,  154,  135,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   43,   43,  155,   43,  155,  153,  153,
      160,   43,  158,  158,   43,   44,   44,  160,   44,  156,
      157,  156,  157,   44,  153,  167,   44,   48,   48,   48,
       48,   48,  167,  156,  157,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   56,   56,  162,  162,  173,
       56,   56,   56,  159,  222,  159,  173,   56,   57,   57,
      164,   57,  163,  163,  165,  159,  212,  169,  169,  164,
      170,  170,  174,  165,  171,  171,   57,   60,   60,  174,
       60,  169,  181,  181,  192,   60,  172,  172,   60,   61,

       61,   61,   61,   61,  187,  187,  172,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   66,   66,   66,
       66,   66,  201,  201,  189,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   72,   72,  183,   72,  177,
      178,  188,  190,  185,  183,  184,   72,  191,  177,  178,
      185,  190,  188,   72,   74,   74,  191,   74,  182,   74,
      193,  168,   74,  166,  161,   74,  152,  193,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   79,   79,   79,
       79,   79,  151,  150,  147,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   85,   85,   85,   85,   85,

      145,  142,  141,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   89,   89,  197,  140,  138,   89,   89,
       89,  131,  198,  129,  197,   89,   94,   94,   94,   94,
       94,  198,  123,  122,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   99,   99,   99,   99,  105,  105,
      121,  105,  119,  105,  105,  105,  105,  105,  115,  105,
      105,  114,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  107,  107,  107,  107,  107,  111,  110,  109,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  117,
      117,  103,  117,  102,  117,   98,  117,  117,   97,   96,

      117,  117,   95,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  118,   93,   91,   88,   84,   83,  118,  118,
       82,  118,  118,  118,  118,  118,  118,  136,   81,   80,
       78,   77,   70,  136,  136,   69,  136,  136,  136,  136,
      136,  136,  139,  139,  139,  139,  175,  175,  175,   67,
      175,  180,  180,   65,   63,  180,   59,   54,   51,   47,
       45,   41,   39,   32,   31,   20,  180,  186,  186,  186,
       17,  186,  194,  194,  194,   14,  194,  195,  195,  195,
       13,  195,  199,  199,  199,    7,  199,  200,  200,  200,
        3,  200,  202,  202,  202,    0,  202,  204,  204,  204,

        0,  204,  205,  205,  205,    0,  205,  207,  207,    0,
      207,    0,  207,  207,  208,    0,    0,  208,  208,  209,
        0,    0,  209,    0,    0,  209,  210,  210,    0,  210,
        0,  210,  210,  211,  211,    0,  211,    0,  211,  211,
      213,  213,    0,  213,    0,  213,  213,  214,  214,    0,
      214,    0,  214,  214,  215,  215,    0,  215,    0,  215,
      215,  216,  216,    0,  216,    0,  216,  216,  217,    0,
        0,  217,    0,    0,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  219,    0,    0,    0,    0,
      219,  220,  220,    0,  220,    0,    0,  220,  221,  221,

      223,  223,    0,  223,    0,    0,  223,  224,  224,    0,
      224,  225,  225,    0,  225,    0,    0,  225,  231,  231,
        0,  231,  232,  232,  232,  232,  232,  234,  234,  234,
      234,  234,  235,  235,    0,  235,  236,  236,  236,  236,
      236,  237,  237,  237,  237,  237,  239,  239,  239,  239,
      239,  240,  240,    0,  240,  241,  241,  241,  241,  241,
      242,  242,  242,  242,  242,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./query.lex"
#line 2 "./query.lex"
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <fstream>
#include <iomanip>
#include "./include/AccumulatorNode.hpp"
#include "./include/hashtable.h"

using namespace std;

const int localHTSize = 50; //query tokens ht size
HashTable localHT(localHTSize); //store query tokens. key field stores query token, data1 stores freq of the query token
const int postingRecSize = 18; //# of char in a posting record
const int DictRecSize = 32; //# of char in a dict file record
const int mapRecSize = 17; //# of char in a map file record
const int numOfResult = 10; //toggle how many top result are shown
const int stopListSize = 18;
//we can implement stop list with regex rule for higher efficiency
string stoplist[stopListSize] = {"the", "and", "of", "to", "in", "for", "is", "on", "be", "this", "are", "will", "by", "that", "you", "with", "as", "or"};
char toLower(char text);
void toLowerArray(char* text, int leng);
bool inStopList(char* text);
int find(const string Key, ifstream &dictFile, const int size, int &numDoc); //find query token position in the dict file.
#line 730 "./query.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 48 "./query.lex"

#line 919 "./query.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 207 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 766 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "./query.lex"
{localHT.Insert(string(yytext));} //insert matched token into localHT
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "./query.lex"
{localHT.Insert(string(yytext));}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "./query.lex"
{localHT.Insert(string(yytext));}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "./query.lex"
{localHT.Insert(string(yytext));}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "./query.lex"
{
				if(yyleng > 1) {
					localHT.Insert(string(yytext));
				}
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "./query.lex"
{localHT.Insert(string(yytext));}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 59 "./query.lex"
; //consume tags
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "./query.lex"
; //consume tags
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "./query.lex"
{
				if(yyleng > 1){
					toLowerArray(yytext, yyleng);
					if(!inStopList(yytext)) {
						localHT.Insert(string(yytext));
					}
				}
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "./query.lex"
{ //abbreviated words
				toLowerArray(yytext, yyleng);
				localHT.Insert(string(yytext));
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "./query.lex"
{
					char *word = strtok(yytext, "-");
					while(word != NULL){
						if (strlen(word) > 1) {
							toLowerArray(word, strlen(word));
							if(!inStopList(word)) {
								localHT.Insert(string(word));
							}
						}
						word = strtok(NULL, "-");
					}
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 85 "./query.lex"
{
			if (yyleng > 1) {
				if(yytext[0] <= 'Z' && yytext[0] >= 'A') {
					yytext[0] = toLower(yytext[0]);
				}
				if(!inStopList(yytext)) {
					localHT.Insert(string(yytext));
				}
			}
		}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 95 "./query.lex"
;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 96 "./query.lex"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "./query.lex"
ECHO;
	YY_BREAK
#line 1113 "./query.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 207 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 207 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 206);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 97 "./query.lex"


int main(int argc, char **argv) {
	if (argc < 2) { //check if argument is valid
		perror ("Invalid argument.\n");
		return 1;
	}
	
	ifstream dictFile("./DictFile.out");
	ifstream postFile("./posting.out");
	ifstream mapFile("./MappingFile.out");
	if(!dictFile || !postFile || !mapFile) { //inverted file open status check
		perror ("Failed opening dict, mapFile, or post file.\n");
		return 1;
	}

	string query;
	for(int i = 1; i < argc; i++){ //combine broken down query arguments
		query.append(argv[i]);
		query.append(" ");
	}
	
	YY_BUFFER_STATE buffer = yy_scan_string(query.c_str()); //tokenize string from buffer instead from a file.
	yylex();
	yy_delete_buffer(buffer);
	
	mapFile.seekg(0, mapFile.end);
	int totalDocCount = mapFile.tellg() / mapRecSize; //calculate number of document
	dictFile.seekg(0, dictFile.end);
	int sizeOfDict = dictFile.tellg() / DictRecSize; //calculate number of records in the dict file
	
	AccumulatorNode weight[totalDocCount]; //weight accumulator
	vector<StringIntPair> record;
	localHT.getNonEmptyEntries(record); //get uniq record
	
	for(int i = 0; i < record.size(); i++) { //process each uniq query token
		int numDoc = 0;
		int startLoc = find(record.at(i).key, dictFile, sizeOfDict, numDoc);
		if(startLoc >= 0) { //if query token is found in dict file
			postFile.seekg(postingRecSize * startLoc);
			int queryTokenFreq = record.at(i).data1; //query token freq
			int docID = 0, freq = 0;
			double wt = 0.0;
			for(int j = 0; j < numDoc; j++) { //read num doc amount of record from posting file
				postFile >> docID >> freq >> wt;
				weight[docID].docId = docID;
				weight[docID].weight = weight[docID].weight + wt * queryTokenFreq;
			}
		}
	}
	
	sort(weight, weight + totalDocCount, [](const AccumulatorNode &a, const AccumulatorNode &b) -> bool {
		return a.weight > b.weight;
	}); //sort best result
	
	if(weight[0].weight != 0.0) { //if there is a query result
		cout << setw(7) << "Ranking" << " " << setw(6) << "Doc ID" << " " << setw(13) << "Document name" << " " << setw(8) << "Weight" << endl;
		for(int i = 0; i < numOfResult; i++) { //loop till hard limit of result displayed
			if(weight[i].weight == 0.0) { //break loop when all result displayed
				break;
			}
			mapFile.seekg(mapRecSize * weight[i].docId);
			int docID;
			string docName;
			mapFile >> docID >> docName;
			cout << setw(7) << i << " " << setw(6) << docID << " " << setw(13) << docName << " " << setw(8) << weight[i].weight << endl;
		}
	} else {
		cout << "No search result found! X_X" << endl;
	}
	
	dictFile.close(); //close file handle
	postFile.close();
	mapFile.close();
}

int find(const string Key, ifstream &dictFile, const int size, int &numDoc) { //return start position of the posting file. -1 means query token is not in the dict file
	unsigned long Sum = 0;
	unsigned long Index;
	
	for (int i = 0; i < Key.length(); i++) {
		Sum = (Sum * 29) + Key[i]; // Mult sum by 29, add byte value of char
	}
	
	Index = Sum % size;
	
	dictFile.seekg(Index * DictRecSize);
	
	string key = "";
	int start = 0;
	double idf = 0.0;
	dictFile >> key >> numDoc >> start >> idf;
	while(key != Key.substr(0, 10) && key != "!null!" && !dictFile.eof()) { //loop till either key is found, empty record, or end of file.
		dictFile >> key >> numDoc >> start >> idf;
	}
	
	if(key != Key.substr(0, 10)) {
		return -1;
	}
	return start;
}

char toLower(char text) {
	return text - 'A' + 'a';
}

void toLowerArray(char* text, int leng) {
	for(int i = 0; i < leng; i++) {
		if(text[i] <= 'Z' && text[i] >= 'A')
			text[i] = toLower(text[i]);
	}
}

bool inStopList(char* text) {
	string txt(text);
	for(int i = 0; i < stopListSize; i++) {
		if(txt == stoplist[i]) {
			return true;
		}
	}
	return false;
}
